// ─── MOCK DATA ───────────────────────────────────────────────────────────────
// Later: replace each export with a real fetch() call to your Express API
// e.g. export const getRecipes = () => fetch('/api/recipes').then(r => r.json())

export const CATEGORIES = ["All", "Desserts", "Italian", "Newari", "Drinks"];

export const RECIPES = [
  {
    id: 1,
    title: "Strawberry Macarons",
    category: "Desserts",
    chef: "Pooja Dhingra",
    chefId: 1,
    rating: 4.8,
    time: "45 mins",
    image: "https://images.unsplash.com/photo-1558326567-98ae2405596b?w=500&q=80",
    description: "Sweet, delicate, and irresistibly berry-flavoured macarons with a crisp shell and chewy centre.",
    ingredients: ["Cream of tartar", "Powdered sugar", "Salt", "Egg whites", "Caster sugar", "Almond flour"],
    instructions: [
      "Line 2 baking sheets with parchment paper. Sift together almond flour and powdered sugar.",
      "Beat egg whites and salt until foamy. Add cream of tartar.",
      "Slowly add caster sugar while beating. Whip until stiff glossy peaks form.",
      "Fold dry ingredients into meringue until lava-like consistency.",
      "Pipe small rounds onto baking sheets. Rest 30 mins until skin forms.",
      "Bake at 150°C for 14-16 minutes. Cool completely before filling.",
    ],
  },
  {
    id: 2,
    title: "Margherita Pizza",
    category: "Italian",
    chef: "Marco Rossi",
    chefId: 2,
    rating: 4.6,
    time: "30 mins",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500&q=80",
    description: "Classic Neapolitan pizza with San Marzano tomatoes and creamy fresh mozzarella.",
    ingredients: ["Pizza dough", "San Marzano tomatoes", "Fresh mozzarella", "Fresh basil", "Olive oil", "Sea salt"],
    instructions: [
      "Preheat oven to 250°C with a pizza stone inside.",
      "Stretch dough on floured surface into a thin round.",
      "Spread crushed tomatoes, tear mozzarella over top.",
      "Bake 10-12 mins until crust is charred and cheese bubbly.",
      "Top with fresh basil and drizzle olive oil. Serve immediately.",
    ],
  },
  {
    id: 3,
    title: "Newari Khaja Set",
    category: "Newari",
    chef: "Sita Maharjan",
    chefId: 3,
    rating: 4.7,
    time: "60 mins",
    image: "https://images.unsplash.com/photo-1567620905732-2d1ec7ab7445?w=500&q=80",
    description: "Traditional Newari feast platter representing the rich culinary heritage of Nepal.",
    ingredients: ["Beaten rice (chiura)", "Buffalo sukuti", "Roasted soybeans", "Potato tarkari", "Spinach saag", "Achar"],
    instructions: [
      "Prepare sukuti by marinating and slow-frying dried buffalo meat.",
      "Roast soybeans until golden. Season with salt and turmeric.",
      "Cook potato tarkari with timur and fenugreek.",
      "Sauté spinach with garlic and mustard oil.",
      "Arrange chiura in centre, surround with all accompaniments.",
      "Serve with tomato achar.",
    ],
  },
  {
    id: 4,
    title: "Boba Tea",
    category: "Drinks",
    chef: "Lisa Chang",
    chefId: 4,
    rating: 4.9,
    time: "20 mins",
    image: "https://images.unsplash.com/photo-1558857563-b371033873b8?w=500&q=80",
    description: "Creamy, sweet and chewy Taiwanese bubble tea made from scratch.",
    ingredients: ["Black tapioca pearls", "Black tea bags", "Whole milk", "Brown sugar syrup", "Ice", "Vanilla extract"],
    instructions: [
      "Cook tapioca pearls per package instructions. Soak in brown sugar syrup.",
      "Brew strong black tea and let cool completely.",
      "Shake tea, milk and ice in a cocktail shaker until frothy.",
      "Add tapioca pearls to glass. Pour tea mixture over.",
      "Serve with a wide straw and enjoy immediately.",
    ],
  },
  {
    id: 5,
    title: "Tiramisu",
    category: "Desserts",
    chef: "Pooja Dhingra",
    chefId: 1,
    rating: 4.5,
    time: "4 hrs",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&q=80",
    description: "Classic Italian no-bake dessert with coffee-soaked ladyfingers and mascarpone cream.",
    ingredients: ["Ladyfinger biscuits", "Mascarpone", "Eggs", "Sugar", "Espresso", "Cocoa powder"],
    instructions: [
      "Separate eggs. Beat yolks with sugar until pale and creamy.",
      "Fold in mascarpone until smooth.",
      "Whip egg whites to stiff peaks, fold into mascarpone mixture.",
      "Dip ladyfingers briefly in cooled espresso.",
      "Layer: cream, ladyfingers, cream. Repeat.",
      "Dust with cocoa, refrigerate 4+ hours.",
    ],
  },
  {
    id: 6,
    title: "Pasta Carbonara",
    category: "Italian",
    chef: "Marco Rossi",
    chefId: 2,
    rating: 4.8,
    time: "25 mins",
    image: "https://images.unsplash.com/photo-1612874742237-6526221588e3?w=500&q=80",
    description: "Authentic Roman carbonara — silky eggs, cured pork and aged cheese. No cream.",
    ingredients: ["Spaghetti", "Guanciale", "Pecorino Romano", "Eggs", "Black pepper", "Salt"],
    instructions: [
      "Cook pasta in well-salted water until al dente. Reserve pasta water.",
      "Fry guanciale until crispy. Remove from heat.",
      "Whisk eggs and grated pecorino together.",
      "Add hot pasta to guanciale pan off heat. Add egg mixture.",
      "Toss vigorously, adding pasta water to create creamy sauce.",
      "Serve with extra pecorino and black pepper.",
    ],
  },
];

export const CHEFS = [
  { id: 1, name: "Pooja Dhingra",  email: "pooja@recipenest.com", bio: "Pastry chef & founder of Le15 Patisserie", recipes: 12, avatar: "👩‍🍳" },
  { id: 2, name: "Marco Rossi",    email: "marco@recipenest.com", bio: "Authentic Italian cuisine specialist from Rome", recipes: 8, avatar: "👨‍🍳" },
  { id: 3, name: "Sita Maharjan",  email: "sita@recipenest.com",  bio: "Traditional Newari food expert from Bhaktapur", recipes: 15, avatar: "👩‍🍳" },
  { id: 4, name: "Lisa Chang",     email: "lisa@recipenest.com",  bio: "Taiwanese food & drinks blogger", recipes: 10, avatar: "👩‍🍳" },
];

export const ADMIN_USERS = [
  { id: 1, name: "Pooja Dhingra", role: "Chef",       recipes: 12 },
  { id: 2, name: "Emma Watson",   role: "Food Lover", recipes: 0  },
  { id: 3, name: "Marco Rossi",   role: "Chef",       recipes: 8  },
  { id: 4, name: "Santosh Shah",  role: "Chef",       recipes: 20 },
  { id: 5, name: "Lisa Chang",    role: "Chef",       recipes: 10 },
];
